### PR TITLE
AIRAVATA-1705 Redisplay form with error when project save fails

### PR DESCRIPTION
**Pull request by machristie**

### CODE REVIEW

**Comment by machristie** [comment]
@scnakandala can you please review this when you get a chance? Thanks.

**Comment by machristie** [comment]
@scnakandala can you review this when you get a chance? Thanks.

**Comment by scnakandala** [comment]
@machristie It seems there is a merge conflict in this pull request

**Comment by machristie** [comment]
@scnakandala thanks, it should be fixed now

**Pull request merged**
